import { cubicInOut } from "svelte/easing"

export const DURATION_TRANSITION_PAGE = 625,
    DURATION_TRANSITION_MODAL = 500,
    DURATION_TRANSITION_PROGRESS_BAR_NAVIGATED = 750,
    DURATION_TRANSITION_MODAL_PROGRESS_BAR_NAVIGATED = 375,
    DURATION_TRANSITION_AFTER_CONTENT_CHANGED = 625,
    DURATION_TRANSITION_TOOLTIP = 400

export const DURATION_RIPPLE_TYPE_ZERO = 400,
    DURATION_RIPPLE_TYPE_ONE = 300,
    DURATION_WAIT_FOR_RIPPLE_TYPE_ONE = DURATION_RIPPLE_TYPE_ONE

export const TRANSITION_PAGE = { y: '1rem', duration: DURATION_TRANSITION_PAGE, easing: cubicInOut }

export const TRANSITION_MODAL_Y = ".5rem"

export const DURATION_TRANSITION_LEFT_MENU_SMALL_SCREEN = 500

export const TRANSITION_FAB = {x: '-.5rem', easing: cubicInOut, delay: DURATION_TRANSITION_PAGE * 1.5},
    TRANSITION_CHANGEABLE_TEXT = {x: '.5rem', duration: DURATION_TRANSITION_AFTER_CONTENT_CHANGED, easing: cubicInOut}