export const EVENT_URL_CHANGING = 'EVENT_URL_CHANGING'

export const EVENT_UNIT_ADDED = 'EVENT_UNIT_ADDED',
    EVENT_UNIT_EDITED = 'EVENT_UNIT_EDITED',
    EVENT_UNIT_REMOVED = 'EVENT_UNIT_REMOVED'

export const EVENT_USER_ADDED = 'EVENT_USER_ADDED',
    EVENT_USER_REMOVED = 'EVENT_USER_REMOVED'

export const EVENT_WORK_ADDED = 'EVENT_WORK_ADDED',
    EVENT_WORK_EDITED = 'EVENT_WORK_EDITED',
    EVENT_WORK_REMOVED = 'EVENT_WORK_REMOVED'